source 'https://github.com/CocoaPods/Specs.git'

target 'JCWheelView_Example', :exclusive => true do
  pod "JCWheelView", :path => "../"
end

target 'JCWheelView_Tests', :exclusive => true do
  pod "JCWheelView", :path => "../"
  
end
